export interface Movie {
  id: number; title: string; year: number; rating: number; genre: string[];
  director: string; cast: string[]; plot: string; tagline: string;
  runtime: string; tmdbId: number; poster: string; backdrop: string;
  _poster?: string; _backdrop?: string;
}

export const movies: Movie[] = [
  { id:1,  title:"Inception",                  year:2010, rating:8.8, genre:["Action","Sci-Fi","Thriller"], director:"Christopher Nolan", cast:["Leonardo DiCaprio","Joseph Gordon-Levitt","Elliot Page","Tom Hardy"], plot:"A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.", tagline:"Your mind is the scene of the crime.", runtime:"2h 28m", tmdbId:27205, poster:"/wwemzKWzjKYJFfCeiB57q3r4Bcm.png", backdrop:"/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg" },
  { id:2,  title:"Midnight in Paris",          year:2011, rating:7.7, genre:["Romance","Comedy","Fantasy"], director:"Woody Allen", cast:["Owen Wilson","Rachel McAdams","Marion Cotillard"], plot:"While on a trip to Paris with his fiancée's family, a nostalgic screenwriter finds himself mysteriously going back to the 1920s every day at midnight.", tagline:"The past is not dead.", runtime:"1h 34m", tmdbId:59436, poster:"/4fH9iPFwV1JSn28mlOqZvPAxQ9.jpg", backdrop:"/bM1iQ2lzD6GAjK7tR3y0gABPLhA.jpg" },
  { id:3,  title:"Mad Max: Fury Road",         year:2015, rating:8.1, genre:["Action","Thriller","Adventure"], director:"George Miller", cast:["Tom Hardy","Charlize Theron","Nicholas Hoult"], plot:"In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper and a drifter named Max.", tagline:"What a lovely day!", runtime:"2h 0m", tmdbId:76341, poster:"/kqjL17yufvn9OVLyXYpvtyrF6ak.jpg", backdrop:"/jz6hRiNHC5W2MpMtl9Q6y7jqC2.jpg" },
  { id:4,  title:"The Green Mile",             year:1999, rating:8.6, genre:["Drama","Mystery","Fantasy"], director:"Frank Darabont", cast:["Tom Hanks","Michael Clarke Duncan","David Morse"], plot:"A tale set on death row, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the lead guard discovers this gift, he struggles to help his charge.", tagline:"Miracles happen in the most unexpected places.", runtime:"3h 9m", tmdbId:497, poster:"/velWPhVMQeQKcxggNEU8YmIo52R.jpg", backdrop:"/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg" },
  { id:5,  title:"Spider-Man: Across the Spider-Verse", year:2023, rating:8.7, genre:["Action","Animation","Sci-Fi","Adventure"], director:"Joaquim Dos Santos", cast:["Shameik Moore","Hailee Steinfeld","Oscar Isaac"], plot:"Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.", tagline:"It's how you wear the mask that matters.", runtime:"2h 20m", tmdbId:569094, poster:"/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg", backdrop:"/nK9i1LwE82M1cNB9vCj4QaBYxM.jpg" },
  { id:6,  title:"The Intouchables",           year:2011, rating:8.5, genre:["Comedy","Drama","Biography"], director:"Olivier Nakache", cast:["François Cluzet","Omar Sy","Anne Le Ny"], plot:"A true story of a wealthy quadriplegic who hires a young man from the projects as his caregiver. Despite their differences, they form an unlikely friendship that changes both their lives.", tagline:"Sometimes you have to reach into someone's world to find your own.", runtime:"1h 52m", tmdbId:77338, poster:"/4DILT3w0078pD202Bx6b9lJqF5I.jpg", backdrop:"/3xB8WmbiW0HVLcsny42r4aTqOBd.jpg" },
  { id:7,  title:"Se7en",                      year:1995, rating:8.6, genre:["Horror","Thriller","Crime","Mystery"], director:"David Fincher", cast:["Morgan Freeman","Brad Pitt","Kevin Spacey"], plot:"Two detectives hunt a serial killer who uses the seven deadly sins as his motives. As they get closer to the truth, they find themselves entangled in a deadly game of cat and mouse.", tagline:"Seven deadly sins. Seven ways to die.", runtime:"2h 7m", tmdbId:807, poster:"/6yoghtyTpznpBik8EngEmJskVUO.jpg", backdrop:"/qUqU7CjPM8sCZ1WL5b7YJNPyF7.jpg" },
  { id:8,  title:"The Lord of the Rings: The Return of the King", year:2003, rating:8.9, genre:["Adventure","Fantasy","Action"], director:"Peter Jackson", cast:["Elijah Wood","Viggo Mortensen","Ian McKellen"], plot:"Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.", tagline:"The eye of the enemy is moving.", runtime:"3h 21m", tmdbId:122, poster:"/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg", backdrop:"/uY2UpTz4w7FJ4T5VjLgXK7q7Yt.jpg" },
  { id:9,  title:"The Social Network",         year:2010, rating:7.8, genre:["Drama","Biography"], director:"David Fincher", cast:["Jesse Eisenberg","Andrew Garfield","Justin Timberlake"], plot:"The story of Mark Zuckerberg's creation of Facebook and the resulting lawsuits that followed. A tale of friendship, ambition, and betrayal in the digital age.", tagline:"You don't get to 500 million friends without making a few enemies.", runtime:"2h 0m", tmdbId:37799, poster:"/n0ybib1C2euzC1n1wuM7hGbq43B.jpg", backdrop:"/j2pRlTJE22zJC2xbYg0q7q0PzM.jpg" },
  { id:10, title:"Interstellar",               year:2014, rating:8.7, genre:["Sci-Fi","Thriller","Adventure","Drama"], director:"Christopher Nolan", cast:["Matthew McConaughey","Anne Hathaway","Jessica Chastain"], plot:"When Earth becomes uninhabitable, a team of explorers travel through a wormhole in search of a new home for humanity. They must make impossible choices to save the human race.", tagline:"Mankind was born on Earth. It was never meant to die here.", runtime:"2h 49m", tmdbId:157336, poster:"/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", backdrop:"/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg" },
  { id:11, title:"Pulp Fiction",               year:1994, rating:8.5, genre:["Crime","Mystery","Thriller"], director:"Quentin Tarantino", cast:["John Travolta","Uma Thurman","Samuel L. Jackson"], plot:"The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption set in Los Angeles.", tagline:"Just because you are a character doesn't mean you have character.", runtime:"2h 34m", tmdbId:680, poster:"/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg", backdrop:"/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg" },
  { id:12, title:"The Lord of the Rings: The Fellowship of the Ring", year:2001, rating:8.4, genre:["Romance","Adventure","Fantasy","Action"], director:"Peter Jackson", cast:["Elijah Wood","Ian McKellen","Orlando Bloom"], plot:"A meek hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.", tagline:"One ring to rule them all.", runtime:"2h 58m", tmdbId:120, poster:"/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg", backdrop:"/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg" },
  { id:13, title:"Avengers: Endgame",          year:2019, rating:8.4, genre:["Sci-Fi","Action","Adventure"], director:"Anthony Russo", cast:["Robert Downey Jr.","Chris Evans","Mark Ruffalo"], plot:"After devastating events wiped out half of all life, the remaining heroes must assemble once more to undo Thanos's actions and restore order to the universe.", tagline:"Avenge the fallen.", runtime:"3h 1m", tmdbId:299534, poster:"/or06FN3Dka5tukK1e9sl16pB3iy.jpg", backdrop:"/7RyHsO4Q7TkYGBQn4QmTqE2DDo.jpg" },
  { id:14, title:"Whiplash",                   year:2014, rating:8.5, genre:["Comedy","Drama","Music"], director:"Damien Chazelle", cast:["Miles Teller","J.K. Simmons","Melissa Benoist"], plot:"A promising young drummer enrolls at a music conservatory where a ruthless instructor will stop at nothing to realize his student's potential.", tagline:"The road to greatness can take you to the edge.", runtime:"1h 47m", tmdbId:244786, poster:"/7fn624j5lj3xTme2SgiLCeuedmO.jpg", backdrop:"/6oCHlhgPjMyFQpy7OC5pXUbFeJM.jpg" },
  { id:15, title:"The Dark Knight",            year:2008, rating:9.0, genre:["Action","Thriller","Crime","Drama"], director:"Christopher Nolan", cast:["Christian Bale","Heath Ledger","Aaron Eckhart"], plot:"When the menace known as the Joker wreaks havoc and chaos on Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.", tagline:"Why so serious?", runtime:"2h 32m", tmdbId:155, poster:"/qJ2tW6WMUDux911BytUrVxM0VpG.jpg", backdrop:"/nMKdUUepR0i5zn0y1T4CsSB5ez.jpg" },
  { id:16, title:"Eternal Sunshine of the Spotless Mind", year:2004, rating:8.3, genre:["Drama","Fantasy","Romance","Sci-Fi"], director:"Michel Gondry", cast:["Jim Carrey","Kate Winslet","Kirsten Dunst"], plot:"When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories. But it's only through the process of loss that they discover what they had.", tagline:"I can't remember anything without you.", runtime:"1h 48m", tmdbId:38, poster:"/5aOHtoidNafSNq4J0tVhUjDmH7k.jpg", backdrop:"/k2g2pVjX1MfvMqJ2y9gKq7vVKq.jpg" },
  { id:17, title:"Alien",                      year:1979, rating:8.2, genre:["Horror","Sci-Fi","Thriller"], director:"Ridley Scott", cast:["Sigourney Weaver","Tom Skerritt","John Hurt"], plot:"The crew of a commercial spacecraft encounters a deadly lifeform after investigating a mysterious transmission on a distant moon. The creature stalks them one by one.", tagline:"In space no one can hear you scream.", runtime:"1h 57m", tmdbId:348, poster:"/vfrQk5IPloGg1v9R2J1QhteY4cH.jpg", backdrop:"/z3nQJ5T1l8F7P2iA1VOo3gLGcv.jpg" },
  { id:18, title:"Full Metal Jacket",          year:1987, rating:8.2, genre:["Action","War","Drama"], director:"Stanley Kubrick", cast:["Matthew Modine","R. Lee Ermey","Vincent D'Onofrio"], plot:"A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting.", tagline:"In Vietnam, the wind doesn't blow. It sucks.", runtime:"1h 56m", tmdbId:600, poster:"/kMKyx1k8hXXZ7QjJGENh30QqWnJ.jpg", backdrop:"/k3GJGVfDG3sP4M2KxQv8C5aV7V.jpg" },
  { id:19, title:"Spirited Away",              year:2001, rating:8.5, genre:["Animation","Family","Fantasy","Adventure"], director:"Hayao Miyazaki", cast:["Daveigh Chase","Suzanne Pleshette","Jason Marsden"], plot:"A young girl wanders into a world ruled by spirits and witches. To save her parents who have been turned into pigs, she must work in a bathhouse for the spirits.", tagline:"The tunnel led to a strange world.", runtime:"2h 5m", tmdbId:129, poster:"/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg", backdrop:"/mS5vSLMlnYTfY7PE5AGK3KzE2I.jpg" },
  { id:20, title:"The Shawshank Redemption",   year:1994, rating:9.3, genre:["Drama","Thriller"], director:"Frank Darabont", cast:["Tim Robbins","Morgan Freeman","Bob Gunton"], plot:"Over the course of several years, two convicts form a friendship, seeking consolation and eventual redemption through basic compassion.", tagline:"Fear can hold you prisoner. Hope can set you free.", runtime:"2h 22m", tmdbId:278, poster:"/9cjIGRQL1m4E87IlVvC8rKaZq9F.jpg", backdrop:"/iXoCH7qJOVWZPmM6lwXgJ2uXHj.jpg" }
]

export const genres = [...new Set(movies.flatMap(m => m.genre))].sort()
